blank_issues_enabled: false
contact_links:
  - name: 📩 Support client MySelfPro
    url: mailto:casis.bouissamatoko@ynov.com
    about: Pour les demandes des utilisateurs freelances (non techniques), avant escalade en anomalie technique.
